# NB7 N-D Searching & Matrices

## Exercise - Landau Section 7.4 (Parts 1, 2, 3, 4): Tests Before Use

- Hint: Work through all the text on Numpy, especially if this is new. There are
many valuable details that illuminate the advantages of using numpy for matrix
calculations.
- This exercise is a way to apply these while exploring some of the linear algebra
tools in the numpy.linalg package.

1) Find the numerical inverse of
$$
\mathbf{A} =
\begin{bmatrix}
+4&−2& +1 \\
+3 &+6&−4 \\
+2 &+1& +8
\end{bmatrix}
$$

    - a) As a general check, applicable even if you do not know the analytic answer, check your inverse in both directions; that is, check that $AA^{−1} = A^{−1}A= I$, and note the number of decimal places to which this is true. This also gives you some idea of the precision of your calculation.
  
    - b) Determine the number of decimal places of agreement there is between your numerical inverse and the analytic result: $
\mathbf{A^{−1}} =
\frac{1}{263}
\begin{bmatrix}
+52 &+17& +2\\
−32 &+30& +19\\
−9&−8 &+30
\end{bmatrix}.
$
        Is this similar to the error in $AA^{−1}$?

In [1]:
import numpy as np
from numpy.linalg import inv # for inv method

A = [[4,-2,1],[3,6,-4],[2,1,8]]
print("A = \n" , np.matrix(A))

Ainv = np.linalg.inv(A)

print("Ainv = \n" , np.matrix(Ainv))

print("\n a) \n")

print(np.dot(A, Ainv))
print(np.dot(Ainv, A))

A = 
 [[ 4 -2  1]
 [ 3  6 -4]
 [ 2  1  8]]
Ainv = 
 [[ 0.19771863  0.06463878  0.00760456]
 [-0.121673    0.11406844  0.07224335]
 [-0.03422053 -0.03041825  0.11406844]]

 a) 

[[ 1.00000000e+00  6.93889390e-18  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  1.00613962e-16]
 [-1.38777878e-17 -4.16333634e-17  1.00000000e+00]]
[[ 1.00000000e+00 -3.46944695e-18  5.55111512e-17]
 [ 2.77555756e-17  1.00000000e+00  2.08166817e-16]
 [ 2.77555756e-17  0.00000000e+00  1.00000000e+00]]


In [2]:
# Analitical Result

coef = (1/263)
mat = [[52,17,2],[-32,30,19],[-9,-8,30]]
Ainvan = np.dot(coef,mat)

print("Ainvan = \n" , np.matrix(Ainvan))

Ainvan - Ainv

Ainvan = 
 [[ 0.19771863  0.06463878  0.00760456]
 [-0.121673    0.11406844  0.07224335]
 [-0.03422053 -0.03041825  0.11406844]]


array([[ 0.00000000e+00,  0.00000000e+00, -6.07153217e-18],
       [ 0.00000000e+00,  1.38777878e-17, -2.77555756e-17],
       [ 0.00000000e+00,  3.46944695e-18, -1.38777878e-17]])


2) Consider the same matrix A as before, here being used to describe three simultaneous
linear equations, $Ax= b$,or explicitly,

$$
\begin{bmatrix}
a_{00} &a_{01} &a_{02} \\
a_{10} &a_{11} &a_{12} \\
a_{20} &a_{21} &a_{22}
\end{bmatrix} \space
\begin{bmatrix}
x_0 \\
x_1 \\
x_2
\end{bmatrix} =
\begin{bmatrix}
b_0 \\
b_1 \\
b_2
\end{bmatrix}.\tag{7.30}
$$

Now the vector **b** on the RHS is assumed known, and the problem is to solve for the
vector **x**. Use an appropriate subroutine to solve these equations for the three different
**x** vectors appropriate to these three different **b** values on the RHS:
$$
\mathbf{b_1} =
\begin{bmatrix}
+12 \\
-25 \\
+32
\end{bmatrix}, \quad
\mathbf{b_2} =
\begin{bmatrix}
+4 \\
-10 \\
+22
\end{bmatrix}, \quad
\mathbf{b_3} =
\begin{bmatrix}
+20 \\
-30 \\
+40
\end{bmatrix}.
$$

The solutions should be

$$
\mathbf{x_1} =
\begin{bmatrix}
+1 \\
-2 \\
+4
\end{bmatrix}, \quad
\mathbf{x_2} =
\begin{bmatrix}
+0.312 \\
-0.038 \\
+2.677
\end{bmatrix}, \quad
\mathbf{x_3} =
\begin{bmatrix}
+2.319 \\
-2.965 \\
+4.790
\end{bmatrix}.\tag{7.31}
$$

In [3]:
bvec = [[12,-25,32],[4,-10,22],[20,-30,40]]
xvec_solve = []

for vec in bvec:
    sol = np.linalg.solve(A, vec)
    xvec_solve.append(sol)

xvec_solve

[array([ 1., -2.,  4.]),
 array([ 0.31178707, -0.03802281,  2.67680608]),
 array([ 2.31939163, -2.96577947,  4.79087452])]

3) Consider the matrix $
A= \begin{bmatrix} \alpha & \beta \\ -\beta & \alpha \end{bmatrix}
$, where you are free to use any values you want for $\alpha$ and $\beta$. Use a numerical eigenvalue solver to show that the eigenvalues and eigenvectors are the complex conjugates.

$$
x_{1,2} = \begin{bmatrix} 1 \\ \mp i \end{bmatrix}, \quad \lambda_{1,2} = \alpha \mp i\beta. \tag{7.32}
$$


In [4]:
import numpy as np
from numpy.linalg import eig

# Define the matrix A with arbitrary values for α and β
alpha = 2
beta = 3
A = [[alpha, beta], [-beta, alpha]]

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(A)

print(f"Eigenvalues: {eigenvalues}\nEigenvectors:\n{eigenvectors}")


Eigenvalues: [2.+3.j 2.-3.j]
Eigenvectors:
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]


4) Use your eigenvalue solver to find the eigenvalues of the matrix

$$
A=
\begin{bmatrix}
-2 & +2 & -3 \\
+2 & +1 & -6 \\
-1 & -2 & 0
\end{bmatrix}. \tag{7.33}
$$

- **a)** Verify that you obtain the eigenvalues $ \lambda_1 = 5 $, $ \lambda_2 = \lambda_3 = -3 $. Beware, double roots can cause problems. In particular, there is a uniqueness issue with their eigenvectors because any combination of these eigenvectors is also an eigenvector.

- **b)** Verify that the eigenvector for $ \lambda_1 = 5 $ is proportional to  

$$
x_1 = \frac{1}{\sqrt{6}}
\begin{bmatrix}
-1 \\
-2 \\
+1
\end{bmatrix}. \tag{7.34}
$$

- **c)** The eigenvalue \( -3 \) corresponds to a double root. This means that the corresponding eigenvectors are degenerate, which in turn means that they are not unique. Two linearly independent ones are:

$$
x_2 = \frac{1}{\sqrt{5}}
\begin{bmatrix}
-2 \\
+1 \\
0
\end{bmatrix}, \quad
x_3 = \frac{1}{\sqrt{10}}
\begin{bmatrix}
3 \\
0 \\
1
\end{bmatrix}. \tag{7.35}
$$

In this case, it’s not clear what your eigenvalue solver will give for the eigenvectors. Try to find a relationship between your computed eigenvectors with the eigenvalue \( -3 \) and these two linearly independent ones.


In [5]:
A = [[-2,2,-3],[2,1,-6],[-1,-2,0]]

print("A = \n" , np.matrix(A))

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(A)

print(f"Eigenvalues: {eigenvalues}\nEigenvectors:\n{eigenvectors}")

A = 
 [[-2  2 -3]
 [ 2  1 -6]
 [-1 -2  0]]
Eigenvalues: [-3.  5. -3.]
Eigenvectors:
[[-0.95257934  0.40824829  0.05155221]
 [ 0.27216553  0.81649658  0.82292764]
 [-0.13608276 -0.40824829  0.5658025 ]]


In [6]:
#input the given values

x1 = np.dot(1/np.sqrt(6),[-1,-2,1])
x2 = np.dot(1/np.sqrt(5),[-2,1,0])
x3 = np.dot(1/np.sqrt(10),[3,0,1])

In [7]:
# Extract the computed eigenvector for λ1 = 5
index_lambda1 = np.where(np.isclose(eigenvalues, 5))[0][0] #compares arrays, picks the true value, slices the index
x1_computed = eigenvectors[:, index_lambda1]

print(x1,x1_computed)

# Check proportionality
scaling_factors_x1 = x1_computed / x1

scaling_factors_x1

[-0.40824829 -0.81649658  0.40824829] [ 0.40824829  0.81649658 -0.40824829]


array([-1., -1., -1.])

In [8]:
# Extract eigenvectors for λ = -3
indices_lambda_23 = np.where(np.isclose(eigenvalues, -3))[0]
x2_computed = eigenvectors[:, indices_lambda_23[0]]
x3_computed = eigenvectors[:, indices_lambda_23[1]]

#linear combinations of x2 and x3
computed_matrix = np.column_stack((x2_computed, x3_computed))
theoretical_matrix = np.column_stack((x2, x3))

coefficients, residuals, rank, singular_values = np.linalg.lstsq(theoretical_matrix, computed_matrix, rcond=None)

coefficients


array([[ 0.60858062,  1.84012215],
       [-0.43033148,  1.7892246 ]])

## (Grad Students) Exercise – landau Section 7.4 (Part 5): Tests Before Use

### **5) Solving a System of Coupled Linear Equations**

Imagine that your model of some physical system results in \( N = 100 \) coupled linear equations in \( N \) unknowns:

$$
a_{00} y_0 + a_{01} y_1 + \dots + a_{0(N-1)} y_{N-1} = b_0,
$$

$$
a_{10} y_0 + a_{11} y_1 + \dots + a_{1(N-1)} y_{N-1} = b_1,
$$

$$
\vdots
$$

$$
a_{(N-1)0} y_0 + a_{(N-1)1} y_1 + \dots + a_{(N-1)(N-1)} y_{N-1} = b_{N-1}.
$$

In many cases, the \( a \) and \( b \) values are known, so your exercise is to solve for all the \( y \) values, taking:

- $ A $ as the **Hilbert matrix**:
  
  $$
  [a_{ij}] = A = \left[ \frac{1}{i + j - 1} \right] =
  \begin{bmatrix}
  1 & \frac{1}{2} & \frac{1}{3} & \dots & \frac{1}{100} \\
  \frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \dots & \frac{1}{101} \\
  \vdots & \vdots & \vdots & \ddots & \vdots \\
  \frac{1}{100} & \frac{1}{101} & \frac{1}{102} & \dots & \frac{1}{199}
  \end{bmatrix}
  $$
  
- $ b $ as its **first column**:

  $$
  [b_i] = b = \left[ \frac{1}{i} \right] =
  \begin{bmatrix}
  1 \\
  \frac{1}{2} \\
  \frac{1}{3} \\
  \vdots \\
  \frac{1}{100}
  \end{bmatrix}
  $$

Compare your computed solution to the **analytic solution**:
$$
    \begin{bmatrix}
    y_1 \\
    y_2 \\
    \vdots \\
    y_N
    \end{bmatrix}
    =
    \begin{bmatrix}
    1 \\
    0 \\
    \vdots \\
    0
    \end{bmatrix}.
    $$


In [9]:
def generate_hilbert_matrix(N):
    """Generate an NxN Hilbert matrix manually using loops."""
    H = np.zeros((N, N))  # Initialize an NxN matrix with zeros
    for i in range(N):
        for j in range(N):
            H[i, j] = 1 / (i + j + 1)  # Hilbert matrix formula
    return H

In [10]:
N = 100

#  Hilbert matrix A (NxN)
A = generate_hilbert_matrix(N)

# vector b (first column of Hilbert matrix)
b = np.array([1 / (i + 1) for i in range(N)])

# Solve the system Ax = b
y = np.linalg.solve(A, b)

print(y)

[ 1.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0.  0.  0.  0. -0. -0. -0.  0.
  0.  0.  0. -0.  0. -0. -0.  0.  0. -0. -0.  0. -0.  0. -0.  0. -0.  0.
 -0. -0.  0.  0.  0. -0.  0. -0.  0. -0. -0.  0. -0.  0.  0.  0. -0. -0.
 -0. -0.  0.  0.  0.  0.  0.  0. -0. -0. -0.  0. -0.  0. -0. -0.  0.  0.
  0. -0.  0.  0.  0. -0. -0. -0.  0. -0.  0.  0. -0. -0. -0. -0. -0. -0.
 -0.  0. -0. -0. -0. -0. -0.  0.  0. -0.]


## Exercise - Landau Section 7.5 (Parts 1 & 2): Solution to String Problem

1) See at what point your initial guess for the angles of the strings gets so bad that the
computer is unable to find a physical solution.

From the book 7.1 code `NewtonNDanimate_NoAnimation` solves 9 coupled equations.

### Geometric Constraints (Position of Strings)

$$
L_1 \cos\theta_1 + L_2 \cos\theta_2 + L_3 \cos\theta_3 = L
$$

$$
L_1 \sin\theta_1 + L_2 \sin\theta_2 - L_3 \sin\theta_3 = 0
$$

### Force Equilibrium Equations (Newton’s Laws)

$$
T_1 \sin\theta_1 - T_2 \sin\theta_2 - W_1 = 0
$$

$$
T_1 \cos\theta_1 - T_2 \cos\theta_2 = 0
$$

$$
T_2 \sin\theta_2 + T_3 \sin\theta_3 - W_2 = 0
$$

$$
T_2 \cos\theta_2 - T_3 \cos\theta_3 = 0
$$

### Trigonometric Identities  
(to treat $\sin\theta$ and $\cos\theta$ as independent)

$$
\sin^2\theta_1 + \cos^2\theta_1 = 1
$$

$$
\sin^2\theta_2 + \cos^2\theta_2 = 1
$$

$$
\sin^2\theta_3 + \cos^2\theta_3 = 1
$$

Since these equations are nonlinear, we solve them iteratively using Newton's Method.


After reviewing the code `NewtonNDanimate_NoAnimation` we see this is a Newton-Raphson problem, from the previos NB we know that the solution may fail to converge if:

- The initial guess is too far from the correct values (x array)
- The iterative process diverges due to a bad conditioning of the Jacobian (deriv)

Let's turn the code into a function that can take initial guesses as parameter for 1)

In [44]:
import numpy as np
from numpy.linalg import inv # for inv method

def newton_nd_solve(initial_guess, eps=1e-3, max_iterations=100,mode='legacy'):
    """
    Solves the nonlinear system of equations for the two-mass, three-string problem
    using Newton's method. As shown in NewtonNDanimate_NoAnimation

    Parameters:
    - initial_guess: array-like, initial values for sin(theta_i), cos(theta_i), and tensions
    - eps: float, convergence tolerance
    - max_iterations: int, maximum number of iterations allowed

    Returns:
    - solution: dictionary containing final values of angles and tensions
    - iterations: number of iterations taken to converge
    - success: boolean indicating whether the method converged

    Use:
    initial_guess = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1., 1.] As in the original code

    should result on 

    Number of iterations =  99 
     Final Solution:
    x[ 0 ] =   0.7610026921018717
    x[ 1 ] =   0.26495381028070264
    x[ 2 ] =   0.8357058293571064
    x[ 3 ] =   0.6487487207029421
    x[ 4 ] =   0.9642611048972874
    x[ 5 ] =   0.549177354575506
    x[ 6 ] =   17.16020978460729
    x[ 7 ] =   11.545279684327756
    x[ 8 ] =   20.271578044639117
    """
    import numpy as np

    # Number of unknowns
    n = 9
    deriv = np.zeros((n, n), float)
    f = np.zeros(n, float)
    #eps = 1e-3 default value on the function parameters
    x = np.array(initial_guess)

    def F(x, f):                                       # F function
        f[0] = 3*x[3]  +  4*x[4]  +  4*x[5]  -  8.0
        f[1] = 3*x[0]  +  4*x[1]  -  4*x[2]
        f[2] = x[6]*x[0]  -  x[7]*x[1]  -  10.0
        f[3] = x[6]*x[3]  -  x[7]*x[4]
        f[4] = x[7]*x[1]  +  x[8]*x[2]  -  20.0
        f[5] = x[7]*x[4]  -  x[8]*x[5]
        # original f6,f7,f8
        if mode == 'legacy':
            f[6] = x[0]**2 + x[3]**2 - 1.0
            f[7] = x[1]**2 + x[4]**2 - 1.0
            f[8] = x[2]**2 + x[5]**2 - 1.0
        elif mode == 'modified': #modified f6,f7,f8 for 2)
            f[6] = x[3] - np.sqrt(max(0, 1 - x[0]**2))
            f[7] = x[4] - np.sqrt(max(0, 1 - x[1]**2))
            f[8] = x[5] - np.sqrt(max(0, 1 - x[2]**2))
        
    def dFi_dXj(x, deriv, n):                           # Derivatives
        h = 1e-4                                             
        for j in range(0, n):
             temp = x[j]
             x[j] = x[j] +  h/2.
             F(x, f)                                                 
             for i in range(0, n):  deriv[i, j] = f[i] 
             x[j] = temp
        for j in range(0, n):
             temp = x[j]
             x[j] = x[j] - h/2.
             F(x, f)
             for i in range(0, n): deriv[i, j] = (deriv[i, j] - f[i])/h
             x[j] = temp
             

    # Newton-Raphson
    for it in range(1, max_iterations + 1):
        # rate(1)                            # 1 second between graphs
        F(x, f)                              
        dFi_dXj(x, deriv, n)   
        B = np.array([[-f[0]], [-f[1]], [-f[2]], [-f[3]], [-f[4]], [-f[5]],\
            [-f[6]], [-f[7]], [-f[8]]])      
        sol = np.linalg.solve(deriv, B)
        dx = np.take(sol, (0, ), 1).flatten()               # First column of sol
        for i in range(0, n):
            x[i]  = x[i]  +  dx[i]
            # plotconfig()
            errX = errF = errXi = 0.0
        for i in range(0, n):
            if ( x[i] !=  0.): errXi = abs(dx[i]/x[i])
            else:  errXi = abs(dx[i])
            if ( errXi > errX): errX = errXi                            
            if ( abs(f[i]) > errF ):  errF = abs(f[i])        
        if ( (errX <=  eps) and (errF <=  eps) ): break #this line in the code from listing is indented wrong causing to always iterate max times

    return {f"x[{i}]": x[i] for i in range(n)}, it, (it < max_iterations)

In [30]:
initial_guess = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1., 1.]
solution, iterations, success = newton_nd_solve(initial_guess)

solution, iterations, success

({'x[0]': np.float64(0.7610026921018719),
  'x[1]': np.float64(0.26495381028070225),
  'x[2]': np.float64(0.8357058293571062),
  'x[3]': np.float64(0.6487487207029418),
  'x[4]': np.float64(0.9642611048972874),
  'x[5]': np.float64(0.5491773545755062),
  'x[6]': np.float64(17.16020978460727),
  'x[7]': np.float64(11.545279684327738),
  'x[8]': np.float64(20.27157804463919)},
 9,
 True)

Ok now that is working let's find some bad guesses like, 
some impossible stuff or things that are not physically allowed

- Extreme angles ($\sin\theta, \cos\theta$ values way outside normal range)
  
  $sinθ = 2.0$ (impossible) or $cosθ = -1.5$ (non-physical).

- Negative and large tensions (physically impossible cases)
  
- Initial tensions set to $-10$ or $10000$.

- Random guesses

In [26]:
guess = [2.0, 1.0, 2.0, 0.01, -1.5, 0.01, -10.0, -10000.0, 10000.0]
solution, iterations, success = newton_nd_solve(guess)

solution, iterations, success

({'x[0]': np.float64(0.7610026921018724),
  'x[1]': np.float64(0.2649538102807103),
  'x[2]': np.float64(0.8357058293571146),
  'x[3]': np.float64(0.6487487207029563),
  'x[4]': np.float64(0.9642611048972869),
  'x[5]': np.float64(0.5491773545754958),
  'x[6]': np.float64(17.160209784606252),
  'x[7]': np.float64(11.545279684326744),
  'x[8]': np.float64(20.271578044640997)},
 36,
 True)

In [28]:
# Random Bull$*(t go!
np.random.seed(42) #obviously
random_guess = np.random.uniform(-100, 100, 9).tolist()

solution, iterations, success = newton_nd_solve(random_guess)

solution, iterations, success, random_guess

({'x[0]': np.float64(0.761002692101863),
  'x[1]': np.float64(0.2649538102807129),
  'x[2]': np.float64(0.8357058293571101),
  'x[3]': np.float64(0.6487487207029529),
  'x[4]': np.float64(0.9642611048972848),
  'x[5]': np.float64(0.5491773545755005),
  'x[6]': np.float64(17.16020978460797),
  'x[7]': np.float64(11.545279684328518),
  'x[8]': np.float64(20.271578044639494)},
 33,
 True,
 [-25.091976230527507,
  90.14286128198324,
  46.39878836228101,
  19.73169683940732,
  -68.79627191151269,
  -68.80109593275947,
  -88.3832775663601,
  73.23522915498702,
  20.223002348641756])

2) A possible problem with the formalism we have just laid out is that by incorporating the
identity $ \sin^2\theta_i + \cos^2\theta_i = 1 $ into the equations, we may be discarding some information
about the sign of $ \sin\theta $ or $ \cos\theta $. If you look at Figure 7.1, you can observe that for some
values of the weights and lengths, $ \theta_2 $ may turn out to be negative, yet $ \cos\theta $ should remain
positive. We can build this condition into our equations by replacing $ f_7 - f_9 $ with $ f' $s
based on the form:

$$
f_7 = x_4 - \sqrt{1 - x_1^2}, \quad
f_8 = x_5 - \sqrt{1 - x_2^2}, \quad
f_9 = x_6 - \sqrt{1 - x_3^2}.
\tag{7.39}
$$

See if this makes any difference in the solutions obtained.

Okay im going to change the calculation of f8, f9, f10 of function newton_nd_solve above

from 
``` python
        f[6] = pow(x[0], 2)  +  pow(x[3], 2)  -  1.0
        f[7] = pow(x[1], 2)  +  pow(x[4], 2)  -  1.0
        f[8] = pow(x[2], 2)  +  pow(x[5], 2)  -  1.0
```

to 

``` python
# Modified conditions for cos(theta)
        f[6] = x[3] - np.sqrt(max(0, 1 - x[0]**2))
        f[7] = x[4] - np.sqrt(max(0, 1 - x[1]**2))
        f[8] = x[5] - np.sqrt(max(0, 1 - x[2]**2))

```

In [24]:
initial_guess = [
    np.sin(np.pi / 4),  
    np.sin(np.pi / 4),  
    np.sin(np.pi / 4),  
    np.cos(np.pi / 4),  
    np.cos(np.pi / 4),  
    np.cos(np.pi / 4),  
    10.0,               
    10.0,                
    10.0                
]

solution_legacy, iterations_legacy, success_legacy = newton_nd_solve(initial_guess, mode='legacy')
solution_modified, iterations_modified, success_modified = newton_nd_solve(initial_guess, mode='modified')

print("Legacy Version:", solution_legacy, iterations_legacy, success_legacy)
print("Modified Version:", solution_modified, iterations_modified, success_modified)

Legacy Version: {'x[0]': np.float64(0.7610026921018729), 'x[1]': np.float64(0.2649538102807012), 'x[2]': np.float64(0.8357058293571059), 'x[3]': np.float64(0.6487487207029408), 'x[4]': np.float64(0.9642611048972878), 'x[5]': np.float64(0.5491773545755066), 'x[6]': np.float64(17.160209784607172), 'x[7]': np.float64(11.545279684327637), 'x[8]': np.float64(20.271578044639423)} 5 True
Modified Version: {'x[0]': np.float64(0.7610026921120219), 'x[1]': np.float64(0.2649538102869575), 'x[2]': np.float64(0.8357058293709739), 'x[3]': np.float64(0.6487487206988066), 'x[4]': np.float64(0.9642611048965519), 'x[5]': np.float64(0.5491773545793432), 'x[6]': np.float64(17.160209784362262), 'x[7]': np.float64(11.545279684053229), 'x[8]': np.float64(20.271578043745098)} 5 True


In [25]:
solution_legacy, iterations_legacy, success_legacy = newton_nd_solve(initial_guess)
solution_modified, iterations_modified, success_modified = newton_nd_solve(initial_guess, mode='modified')

# Print results
print_solution("Legacy", solution_legacy, iterations_legacy, success_legacy)
print_solution("Modified", solution_modified, iterations_modified, success_modified)


Legacy Version:
  Converged: Yes in 5 iterations
  Final Solution:
    x[0] = 0.7610026921
    x[1] = 0.2649538103
    x[2] = 0.8357058294
    x[3] = 0.6487487207
    x[4] = 0.9642611049
    x[5] = 0.5491773546
    x[6] = 17.1602097846
    x[7] = 11.5452796843
    x[8] = 20.2715780446

Modified Version:
  Converged: Yes in 5 iterations
  Final Solution:
    x[0] = 0.7610026921
    x[1] = 0.2649538103
    x[2] = 0.8357058294
    x[3] = 0.6487487207
    x[4] = 0.9642611049
    x[5] = 0.5491773546
    x[6] = 17.1602097844
    x[7] = 11.5452796841
    x[8] = 20.2715780437


In [6]:
#That looks awful let me reprint

def print_solution(name, solution, iterations, success):
    print(f"\n{name} Version:")
    print(f"  Converged: {'Yes' if success else 'No'} in {iterations} iterations")
    print("  Final Solution:")
    for key, value in solution.items():
        print(f"    {key} = {value:.10f}")

In [29]:
solution_legacy, iterations_legacy, success_legacy = newton_nd_solve(random_guess)
solution_modified, iterations_modified, success_modified = newton_nd_solve(random_guess, mode='modified')

print_solution("Legacy", solution_legacy, iterations_legacy, success_legacy)
print_solution("Modified", solution_modified, iterations_modified, success_modified)

LinAlgError: Singular matrix

What im getting is that if the initial guess is not good enough, the jacobian is not invertible
and we don't get a solution out of it. Funny since without account for sign change we did get solutions


For this to work, or at least dont pop up an error we need to make sure the matrix is invertible
then prompt the user to give a better guess if it isn't. Or said it wont converge try another guess

3) ⊙ Solve the similar three-mass problem. The approach is the same, but the number of
equations is larger.

In [71]:
import numpy as np
from numpy.linalg import inv  # for inv method

def newton_nd_solve(initial_guess, eps=1e-3, max_iterations=100, mode='legacy', masses=3):
    """
    Solves the nonlinear system of equations for the multi-mass, multi-string problem
    using Newton's method.

    Parameters:
    - initial_guess: array-like, initial values for sin(theta_i), cos(theta_i), and tensions
    - eps: float, convergence tolerance
    - max_iterations: int, maximum number of iterations allowed
    - mode: str, 'legacy' for the original method, 'modified' for handling sign constraints
    - masses: int, number of masses in the system (supports any N masses)

    Returns:
    - solution: dictionary containing final values of angles and tensions
    - iterations: number of iterations taken to converge
    - success: boolean indicating whether the method converged
    """
    n = 3 * (masses + 1)  # Corrected number of unknowns for N masses
    deriv = np.zeros((n, n), float)
    f = np.zeros(n, float)
    x = np.array(initial_guess)

    
    def F(x, f):
        # Force balance equations for each mass

        #f[0] = 3*x[3]  +  4*x[4]  +  4*x[5]  -  8.0 2masses 
        f[0] = 3*x[4] + 4*x[5] + 4*x[6] + 5*x[7] - 8.0
        #f[2] = x[6]*x[0]  -  x[7]*x[1]  -  10.0
        f[2] = x[8]*x[0] - x[9]*x[1] - 10.0
        #f[4] = x[7]*x[1]  +  x[8]*x[2]  -  20.0
        f[4] = x[9]*x[1] + x[10]*x[2] - 20.0
        f[6] = x[10]*x[2] + x[11]*x[3] - 30.0

        #f[1] = 3*x[0]  +  4*x[1]  -  4*x[2]
        f[1] = 3*x[0] + 4*x[1] + 5*x[2] - 5*x[3]
        #f[3] = x[6]*x[3]  -  x[7]*x[4]
        f[3] = x[8]*x[4] - x[9]*x[5]
        #f[5] = x[7]*x[4]  -  x[8]*x[5]
        f[5] = x[9]*x[5] - x[10]*x[6]
        f[7] = x[10]*x[6] - x[11]*x[7]

        #2 aditional equations
        
        # Trigonometric constraints
        if mode == 'legacy':
            #f[6] = x[0]**2 + x[3]**2 - 1.0 now is 8
            f[8] = x[0]**2 + x[4]**2 - 1.0

            #f[7] = x[1]**2 + x[4]**2 - 1.0 now is 9
            f[9] = x[1]**2 + x[5]**2 - 1.0

            #f[8] = x[2]**2 + x[5]**2 - 1.0 now is 10
            f[10] = x[2]**2 + x[6]**2 - 1.0

            #1 additional eq
            f[11] = x[3]**2 + x[7]**2 - 1.0
        elif mode == 'modified':
            f[8] = x[4] - np.sqrt(max(0, 1 - x[0]**2))
            f[9] = x[5] - np.sqrt(max(0, 1 - x[1]**2))
            f[10] = x[6] - np.sqrt(max(0, 1 - x[2]**2))
            f[11] = x[7] - np.sqrt(max(0, 1 - x[3]**2))
        
    def dFi_dXj(x, deriv, n):                           # Derivatives
        h = 1e-4                                             
        for j in range(0, n):
             temp = x[j]
             x[j] = x[j] +  h/2.
             F(x, f)                                                 
             for i in range(0, n):  deriv[i, j] = f[i] 
             x[j] = temp
        for j in range(0, n):
             temp = x[j]
             x[j] = x[j] - h/2.
             F(x, f)
             for i in range(0, n): deriv[i, j] = (deriv[i, j] - f[i])/h
             x[j] = temp
             

    # Newton-Raphson
    for it in range(1, max_iterations + 1):
        # rate(1)                            # 1 second between graphs
        F(x, f)                              
        dFi_dXj(x, deriv, n)   
        B = np.array([[-f[i]] for i in range(n)])    
        sol = np.linalg.solve(deriv, B)
        dx = np.take(sol, (0, ), 1).flatten()               # First column of sol
        for i in range(0, n):
            x[i]  = x[i]  +  dx[i]
            # plotconfig()
            errX = errF = errXi = 0.0
        for i in range(0, n):
            if ( x[i] !=  0.): errXi = abs(dx[i]/x[i])
            else:  errXi = abs(dx[i])
            if ( errXi > errX): errX = errXi                            
            if ( abs(f[i]) > errF ):  errF = abs(f[i])        
        if ( (errX <=  eps) and (errF <=  eps) ): break #this line in the code from listing is indented wrong causing to always iterate max times

    return {f"x[{i}]": x[i] for i in range(n)}, it, (it < max_iterations)


In [72]:
masses = 3

In [73]:
def generate_initial_guess(masses):
    angles = np.linspace(np.pi/6, np.pi/3, masses + 1)  # Spread angles between 30° and 60°
    initial_guess = []

    # sin(theta) and cos(theta) values
    for theta in angles:
        initial_guess.append(np.sin(theta))  # sin(theta_i)
    for theta in angles:
        initial_guess.append(np.cos(theta))  # cos(theta_i)

    # Tensions: reasonable initial tensions
    initial_guess.extend([10.0] * (masses + 1))  # Set all tensions to 10.0

    return initial_guess

initial_guess = generate_initial_guess(masses)
print("Initial Guess:", "[" + ", ".join(f"{x:.6f}" for x in initial_guess) + "]")
len(initial_guess)

Initial Guess: [0.500000, 0.642788, 0.766044, 0.866025, 0.866025, 0.766044, 0.642788, 0.500000, 10.000000, 10.000000, 10.000000, 10.000000]


12

In [74]:
solution, iterations, success = newton_nd_solve(initial_guess, masses)
print_solution(f"{masses} mases", solution, iterations, success)


3 mases Version:
  Converged: Yes in 8 iterations
  Final Solution:
    x[0] = 0.9491672053
    x[1] = 0.9055905028
    x[2] = -0.3446602539
    x[3] = 0.9493124715
    x[4] = 0.3167081042
    x[5] = 0.4264401825
    x[6] = 0.9414536300
    x[7] = 0.3156600875
    x[8] = 36.0259814125
    x[9] = 26.7521923849
    x[10] = 11.9290018778
    x[11] = 36.0711488677


## Exercise - Landau Section 7.7.2 (Parts 1, 2, 3, 4, 5): Speed up exercises

- IMPORTANT: Make clear which work is for each part and add a short description
summarizing your observations for each part.
- Hint: Working through the examples in 7.7.1 first will help you.

1) Timing an operation

In [15]:
import time
start = time.time()
print("hello" )
end = time.time()
print(end - start )

hello
4.482269287109375e-05


In this one we are importing a pkg for run time execution. 
we record the time at the very beginning 
then run code, record the time afterwards. Get the diference to see how long it took to run

2) Run the two simple codes listed below, timing how long each takes. Note that although
each has the same number of arithmetic operations, one takes significantly more time
because it makes large jumps through memory.

### Sequential column references

``` pseudocode
for j = 1, 999999;
x(j) = m(1, j) // Sequential column reference
```

In [16]:
size = 10000  # Adjust based on available memory
m = [[0 for _ in range(size)] for _ in range(size)]

In [17]:
import time
start = time.time()
x = [0] * size

for j in range(size):
    x = m[0][j] #Sequential column reference

end = time.time()

print(end - start)

0.0007290840148925781


### Sequential row references
``` pseudocode
    for j = 1, 999999;
2   x(j) = m(j ,1) // Sequential row reference
```

In [18]:
import time
start = time.time()
x = [0] * size

for j in range(size):
    x = m[j][0] #Sequential column reference

end = time.time()

print(end - start)

0.003002166748046875


This code is going though a zeros matrix of size x size. And slicing first row then first column and moving through it as it fills a vector with 0 from those parts of the matrix. We can see it takes significantly more time to do this in the comlumn part that in rows by an order of magnitude. At least in my machine

3) Test the effect of stride on your machine by comparing the time it takes to run these two
programs. Run for increasing column size `idiom` and compare the times for loop A versus
those for loop B. Loop A steps through the matrix vec in column order, while loop B steps
through in row order. Both loops take us through all the elements of the matrix, but the
stride is different.

### Loop A bad (large) stride

```pseudocode
    Dimension vec(N, M) // Stride 1 fetch (f90)
2   for j = 1, M;
    for i=1, N; Ansi = Ansi + vec(i , j)∗ vec(i , j)
```

In [19]:
import numpy as np
import time
N, M = 10000, 10000

# Create a large matrix filled with random values
vec = np.random.rand(N, M)

In [20]:
start = time.time()

# Loop A: Column-wise access (bad stride (step size in memory))
Ansi = 0.0
for j in range(M):  # Iterate over columns first
    for i in range(N):  # Iterate over rows second 
        Ansi += vec[i, j] * vec[i, j]  

end = time.time()

print(end - start)

35.72884202003479


### Loop B good (small) stride
```pseudocode
1   Dimension vec(N, M) // Stride dim fetch (f90)
    for i = 1, N;
    for j=1, M; Ansi = Ansi + vec(i , j)∗ vec(i , j)
```

In [21]:
start = time.time()
ansi = 0
for i in range(N):    # Iterate over rows first
    for j in range(M):
        ansi += vec[i, j] * vec[i, j]
end = time.time()
print(end - start)

35.74391794204712
